### ISSUE TITLE
info

### ISSUE THREAD

**Issue by carlostuuling** [carlostuuling/projekt-2#1]
ajalugu
pildid
töö 
näitused
hind

**Comment by GregorTilts** [comment]
Navitrolla lõpetas Viive Kuksi kolmeaastase kunstistuudio.

**Comment by GregorTilts** [comment]
Õppis Tartu Ülikoolis geoloogiat, proovis astuda Eesti Kunstiakadeemiasse õppima arhitektuuri ja maali, kuid ei läbinud konkurssi.

**Comment by GregorTilts** [comment]
Aastast 1993 oli ta vabakutseline kunstnik. Naivistlik maalimislaad tõi talle kiiresti tuntuse.

**Comment by GregorTilts** [comment]
Aastail 1997–2001 pidas Navitrolla kunstigaleriid nii Tallinnas kui ka Tartus.

**Comment by GregorTilts** [comment]
Praegu asub ainus Navitrolla galerii Tallinna vanalinnas.

**Comment by GregorTilts** [comment]
Navitrolla elab ja töötab Lõuna-Eestis.

**Comment by GregorTilts** [comment]
![image](https://user-images.githubusercontent.com/92710301/140273876-9e036250-0b7f-4755-93cd-f1a1e1e9d805.png)

**Comment by GregorTilts** [comment]
![image](https://user-images.githubusercontent.com/92710301/140274172-b5dc5de6-7dab-4921-b2fd-1439e11e2129.png)

**Comment by GregorTilts** [comment]
![image](https://user-images.githubusercontent.com/92710301/140275020-dfdb5fa2-1f97-4f95-90c7-0f3afcbb52f2.png)

**Comment by GregorTilts** [comment]
Viljelenud maali, graafikat ja tegevuskunsti, rohkesti töid on avaldatud postkaartidel ja kalendrites.

**Comment by GregorTilts** [comment]
Sagedaseks motiiviks on mitmesugused loomad nende jaoks harjumatus keskkonnas ja unenäoliste maastike taustal (nt troopilisele Aafrikale omased loomad põhjamaises looduses).
